# -*- coding: utf-8 -*-
"""numpy operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bmhyej-zbqPjbF-um5uFnP9mBL9dbYm1
"""

pip install numpy

import numpy as np

print(np.__version__)

import numpy as np
arr =np.array([1,2,3,4,5,6,])
print(arr)

import numpy as np
arr = np.array([[1,2,3],[4,5,6,]])
print(arr)

import numpy as np
arr =np.array([[1,2],[3,4],[5,6]])
print(arr)
print(type)



import numpy as np
arr = np.zeros((5,5))
print(arr)

import numpy as np
arr = np.zeros((10,3))
print(arr)

arr = np.ones((3,1))
arr

arr=np.full((4,7),9)
arr

arr = np.empty((5,5))
arr

import numpy as np
arr = np.eye(5)
arr

import numpy as np
arr = np.arange(2,500,2)
arr

arr = np.arange(1,500,2)
arr

arr = np.linspace(1,10,5)
arr

arr = np.random.rand(10)
arr

arr = np.random.randn(10)
arr

import numpy as np
colours = ["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

ray([1,2,3])arr = np.ar
new = arr.copy()
new[1] = 100
print("Array value is:", arr)
print("copy value is:",new)

import numpy as np
arr = np.array([5,10,15,20,25,30])
arr += 10
print("Updated array value is:", arr)

import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))

import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.divide(A,B))

import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

import numpy as np
Arr = np.array([1,2,3,4,5,6,7,8,9])
print(sum(Arr))

import numpy as np
Arr = np.array([1,2,9,13,3,4,5,6,7,8,9])
print(np.sort(Arr))

import numpy as np
Arr = np.array([1,2,9,13,3,4,5,6,7,8,9])
print(np.unique(Arr))

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.size)
print(arr.dtype)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.ndim)
print(arr[1,7])

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Original Array", arr)
newarr = arr.reshape(3,5)
print("Reshaped Array", newarr)

